namespace SymmetricDS.Admin
{
    public enum Databases
    {
        AmazonRedshift,
        ApacheDerby,
        ApacheIgnite,
        Firebird,
        Greenplum,
        DB24LUW,
        DB24i,
        DB24zOS,
        H2,
        HSQLDB,
        Informix,
        Interbase,
        MariaDB,
        MongoDB,
        MySQL,
        NuoDB,
        Oracle,
        PostgreSQL,
        SQLAnywhere,
        SQLServer,
        SQLServerAzure,
        SQLite,
        SybaseASE,
        Tibero,
        VoltDB
    }
}